services:
  jenkins:
    image: custom-jenkins:latest  # The custom Jenkins image
    user: root
    container_name: jenkins-blueocean      # Name of the container
    ports:
      - "8080:8080"                         # Map port 8080 for the Jenkins UI
      - "50000:50000"                       # Map port 50000 for agent communication
    volumes:
      - jenkins-data:/var/jenkins_home     # Define the volume for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket for communication with the Docker daemon
    networks:
      - jenkins                             # Network to connect Jenkins with other services, if any
    environment:
      JAVA_OPTS: -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts; default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"

#    jenkins-agent:
#      image: jenkins/inbound-agent
#      user: root
#      container_name: jenkins-agent
#      environment:
#        - JENKINS_URL=http://jenkins:8080  # URL of Jenkins master
#        - JENKINS_SECRET=b209cdde9997f8f9c70939937741b2d32d102934a980c8acf6b9a419c9358306    # Agent secret (replace with actual secret)
#        - JENKINS_AGENT_NAME=agent1  # Name of the Jenkins agent
#        - JENKINS_AGENT_WORKDIR=/home/jenkins/agent  # Work directory for the agent
#      volumes:
#        - jenkins_agent_home:/home/jenkins/agent  # Create a volume for the agent workspace
#        - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for communication
#      networks:
#        - jenkins
#      depends_on:
#        - jenkins

  jenkins-agent:
    image: jenkins/agent  # Official Docker image with Docker CLI installed
    user: root
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=your_secret
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - jenkins_agent_home:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket to access host Docker daemon
    networks:
      - jenkins
    depends_on:
      - jenkins


volumes:
  jenkins-data:  # Global volume declaration for persisting Jenkins data
  jenkins_agent_home:

networks:
  jenkins:
    driver: bridge  # Define the network driver