---
- name: Install and Configure Jenkins
  hosts: jenkins_server
  become: true

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Java 17 (Amazon Corretto)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Wait for Jenkins to fully start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Retrieve Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Print Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"

    - name: Save Jenkins initial admin password to a local file
      delegate_to: localhost
      become: false
      copy:
        content: "{{ jenkins_password.stdout }}"
        dest: "./jenkins_initial_admin_password.txt"
        mode: '0600'